### ISSUE TITLE
Problemi di installazione su PostgreSQL

### ISSUE THREAD

**Issue by Cavva79** [ProgettoArchimista/archimista#4]
Salve,

sto tentando di installare Archimista 3 su postgresql 9.4.5, attualmente ricevo questi errori:

```
-- create_table("activities", {:force=>:cascade})
   -> 0.0283s
-- add_index("activities", ["db_source", "legacy_id"], {:name=>"index_activities_on_source_and_legacy_id", :using=>:btree})
   -> 0.0059s
-- create_table("creator_activities", {:force=>:cascade})
   -> 0.0085s
-- add_index("creator_activities", ["creator_id"], {:name=>"index_creator_activities_on_creator_id", :using=>:btree})
   -> 0.0058s
-- add_index("creator_activities", ["db_source", "legacy_id"], {:name=>"index_creator_activities_on_source_and_legacy_id", :using=>:btree})
   -> 0.0054s
-- create_table("creator_association_types", {:force=>:cascade})
   -> 0.0057s
-- create_table("creator_corporate_types", {:force=>:cascade})
   -> 0.0055s
-- create_table("creator_editors", {:force=>:cascade})
   -> 0.0090s
-- add_index("creator_editors", ["creator_id"], {:name=>"index_creator_editors_on_creator_id", :using=>:btree})
   -> 0.0056s
-- add_index("creator_editors", ["db_source", "legacy_id"], {:name=>"index_creator_editors_on_source_and_legacy_id", :using=>:btree})
   -> 0.0056s
-- create_table("creator_events", {:force=>:cascade})
rake aborted!
ActiveRecord::StatementInvalid: PG::SyntaxError: ERROR:  syntax error at or near "("
LINE 1: SELECT 'boolean(1)'::regtype::oid
               ^
CONTEXT:  invalid type name "boolean(1)"
: SELECT 'boolean(1)'::regtype::oid
/usr/local/bundle/gems/activerecord-4.2.1/lib/active_record/connection_adapters/postgresql/database_statements.rb:155:in `async_exec'
/usr/local/bundle/gems/activerecord-4.2.1/lib/active_record/connection_adapters/postgresql/database_statements.rb:155:in `block in execute'
/usr/local/bundle/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract_adapter.rb:473:in `block in log'
/usr/local/bundle/gems/activesupport-4.2.1/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/usr/local/bundle/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract_adapter.rb:467:in `log'
/usr/local/bundle/gems/activerecord-4.2.1/lib/active_record/connection_adapters/postgresql/database_statements.rb:154:in `execute'
/usr/local/bundle/gems/activerecord-4.2.1/lib/active_record/connection_adapters/postgresql_adapter.rb:393:in `lookup_cast_type'
/usr/local/bundle/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract/schema_creation.rb:120:in `type_for_column'
/usr/local/bundle/gems/activerecord-4.2.1/lib/active_record/connection_adapters/postgresql/schema_statements.rb:33:in `type_for_column'
/usr/local/bundle/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract/schema_creation.rb:97:in `quote_value'
/usr/local/bundle/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract/schema_creation.rb:84:in `add_column_options!'
/usr/local/bundle/gems/activerecord-4.2.1/lib/active_record/connection_adapters/postgresql/schema_statements.rb:25:in `add_column_options!'
/usr/local/bundle/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract/schema_creation.rb:33:in `visit_ColumnDefinition'
/usr/local/bundle/gems/activerecord-4.2.1/lib/active_record/connection_adapters/postgresql/schema_statements.rb:8:in `visit_ColumnDefinition'
/usr/local/bundle/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract/schema_creation.rb:14:in `accept'
/usr/local/bundle/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract/schema_creation.rb:40:in `block in visit_TableDefinition'
/usr/local/bundle/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract/schema_creation.rb:40:in `map'
/usr/local/bundle/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract/schema_creation.rb:40:in `visit_TableDefinition'
/usr/local/bundle/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract/schema_creation.rb:14:in `accept'
/usr/local/bundle/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract/schema_statements.rb:208:in `create_table'
/usr/local/bundle/gems/activerecord-4.2.1/lib/active_record/migration.rb:662:in `block in method_missing'
/usr/local/bundle/gems/activerecord-4.2.1/lib/active_record/migration.rb:632:in `block in say_with_time'
/usr/local/bundle/gems/activerecord-4.2.1/lib/active_record/migration.rb:632:in `say_with_time'
/usr/local/bundle/gems/activerecord-4.2.1/lib/active_record/migration.rb:652:in `method_missing'
/archimista/db/schema.rb:73:in `block in <top (required)>'
/usr/local/bundle/gems/activerecord-4.2.1/lib/active_record/schema.rb:41:in `instance_eval'
/usr/local/bundle/gems/activerecord-4.2.1/lib/active_record/schema.rb:41:in `define'
/usr/local/bundle/gems/activerecord-4.2.1/lib/active_record/schema.rb:61:in `define'
/archimista/db/schema.rb:14:in `<top (required)>'
/usr/local/bundle/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:268:in `load'
/usr/local/bundle/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:268:in `block in load'
/usr/local/bundle/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:240:in `load_dependency'
/usr/local/bundle/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:268:in `load'
/usr/local/bundle/gems/activerecord-4.2.1/lib/active_record/tasks/database_tasks.rb:218:in `load_schema_for'
/usr/local/bundle/gems/activerecord-4.2.1/lib/active_record/tasks/database_tasks.rb:235:in `block in load_schema_current'
/usr/local/bundle/gems/activerecord-4.2.1/lib/active_record/tasks/database_tasks.rb:275:in `block in each_current_configuration'
/usr/local/bundle/gems/activerecord-4.2.1/lib/active_record/tasks/database_tasks.rb:274:in `each'
/usr/local/bundle/gems/activerecord-4.2.1/lib/active_record/tasks/database_tasks.rb:274:in `each_current_configuration'
/usr/local/bundle/gems/activerecord-4.2.1/lib/active_record/tasks/database_tasks.rb:234:in `load_schema_current'
/usr/local/bundle/gems/activerecord-4.2.1/lib/active_record/railties/databases.rake:244:in `block (3 levels) in <top (required)>'
/usr/local/bundle/gems/activerecord-4.2.1/lib/active_record/railties/databases.rake:248:in `block (3 levels) in <top (required)>'
/usr/local/bundle/gems/rake-12.3.0/exe/rake:27:in `<top (required)>'

Caused by:
PG::SyntaxError: ERROR:  syntax error at or near "("
LINE 1: SELECT 'boolean(1)'::regtype::oid
               ^
CONTEXT:  invalid type name "boolean(1)"
/usr/local/bundle/gems/activerecord-4.2.1/lib/active_record/connection_adapters/postgresql/database_statements.rb:155:in `async_exec'
/usr/local/bundle/gems/activerecord-4.2.1/lib/active_record/connection_adapters/postgresql/database_statements.rb:155:in `block in execute'
/usr/local/bundle/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract_adapter.rb:473:in `block in log'
/usr/local/bundle/gems/activesupport-4.2.1/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/usr/local/bundle/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract_adapter.rb:467:in `log'
/usr/local/bundle/gems/activerecord-4.2.1/lib/active_record/connection_adapters/postgresql/database_statements.rb:154:in `execute'
/usr/local/bundle/gems/activerecord-4.2.1/lib/active_record/connection_adapters/postgresql_adapter.rb:393:in `lookup_cast_type'
/usr/local/bundle/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract/schema_creation.rb:120:in `type_for_column'
/usr/local/bundle/gems/activerecord-4.2.1/lib/active_record/connection_adapters/postgresql/schema_statements.rb:33:in `type_for_column'
/usr/local/bundle/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract/schema_creation.rb:97:in `quote_value'
/usr/local/bundle/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract/schema_creation.rb:84:in `add_column_options!'
/usr/local/bundle/gems/activerecord-4.2.1/lib/active_record/connection_adapters/postgresql/schema_statements.rb:25:in `add_column_options!'
/usr/local/bundle/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract/schema_creation.rb:33:in `visit_ColumnDefinition'
/usr/local/bundle/gems/activerecord-4.2.1/lib/active_record/connection_adapters/postgresql/schema_statements.rb:8:in `visit_ColumnDefinition'
/usr/local/bundle/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract/schema_creation.rb:14:in `accept'
/usr/local/bundle/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract/schema_creation.rb:40:in `block in visit_TableDefinition'
/usr/local/bundle/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract/schema_creation.rb:40:in `map'
/usr/local/bundle/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract/schema_creation.rb:40:in `visit_TableDefinition'
/usr/local/bundle/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract/schema_creation.rb:14:in `accept'
/usr/local/bundle/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract/schema_statements.rb:208:in `create_table'
/usr/local/bundle/gems/activerecord-4.2.1/lib/active_record/migration.rb:662:in `block in method_missing'
/usr/local/bundle/gems/activerecord-4.2.1/lib/active_record/migration.rb:632:in `block in say_with_time'
/usr/local/bundle/gems/activerecord-4.2.1/lib/active_record/migration.rb:632:in `say_with_time'
/usr/local/bundle/gems/activerecord-4.2.1/lib/active_record/migration.rb:652:in `method_missing'
/archimista/db/schema.rb:73:in `block in <top (required)>'
/usr/local/bundle/gems/activerecord-4.2.1/lib/active_record/schema.rb:41:in `instance_eval'
/usr/local/bundle/gems/activerecord-4.2.1/lib/active_record/schema.rb:41:in `define'
/usr/local/bundle/gems/activerecord-4.2.1/lib/active_record/schema.rb:61:in `define'
/archimista/db/schema.rb:14:in `<top (required)>'
/usr/local/bundle/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:268:in `load'
/usr/local/bundle/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:268:in `block in load'
/usr/local/bundle/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:240:in `load_dependency'
/usr/local/bundle/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:268:in `load'
/usr/local/bundle/gems/activerecord-4.2.1/lib/active_record/tasks/database_tasks.rb:218:in `load_schema_for'
/usr/local/bundle/gems/activerecord-4.2.1/lib/active_record/tasks/database_tasks.rb:235:in `block in load_schema_current'
/usr/local/bundle/gems/activerecord-4.2.1/lib/active_record/tasks/database_tasks.rb:275:in `block in each_current_configuration'
/usr/local/bundle/gems/activerecord-4.2.1/lib/active_record/tasks/database_tasks.rb:274:in `each'
/usr/local/bundle/gems/activerecord-4.2.1/lib/active_record/tasks/database_tasks.rb:274:in `each_current_configuration'
/usr/local/bundle/gems/activerecord-4.2.1/lib/active_record/tasks/database_tasks.rb:234:in `load_schema_current'
/usr/local/bundle/gems/activerecord-4.2.1/lib/active_record/railties/databases.rake:244:in `block (3 levels) in <top (required)>'
/usr/local/bundle/gems/activerecord-4.2.1/lib/active_record/railties/databases.rake:248:in `block (3 levels) in <top (required)>'
/usr/local/bundle/gems/rake-12.3.0/exe/rake:27:in `<top (required)>'
Tasks: TOP => db:schema:load
(See full trace by running task with --trace)
```

A quanto mi risulta, per avere compatibilità con Postgres, la definizione di BOOLEAN non dovrebbe contenere (1)

**Comment by svassallo** [comment]
Dovrebbe esser stato risolto https://github.com/rails/rails/issues/19065

ma non saprei dire in quale versione di rails

**Comment by Cavva79** [comment]
Grazie @svassallo 

sembra che il problema sia rails 2.2.X

Cmq ho risolto passando a rails 2.1.9.
